//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        public candidato()
        {
            this.tecnologia = new HashSet<tecnologia>();
        }
    
        public int idCandidato { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string palabrasClave { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idReclutador { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual ICollection<tecnologia> tecnologia { get; set; }
    }
}
