//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        public candidato()
        {
            this.tecnologia = new HashSet<tecnologia>();
        }

        public System.DateTime fecha_registro { get; set; }
        public int idPersona { get; set; }
        public int idReclutador { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual reclutador reclutador { get; set; }
        public virtual ICollection<tecnologia> tecnologia { get; set; }
    }
}
