//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.candidato = new HashSet<candidato>();
            this.reclutador = new HashSet<reclutador>();
        }
    
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public string apePaterno { get; set; }
        public string apeMaterno { get; set; }
    
        public virtual ICollection<candidato> candidato { get; set; }
        public virtual ICollection<reclutador> reclutador { get; set; }
    }
}
