//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tecnologia
    {
        public tecnologia()
        {
            this.candidato = new HashSet<candidato>();
        }
    
        [Key]
        public int idTecnologia { get; set; }
        [DataType(DataType.Text, ErrorMessage = "En este campo sólo se permite texto")]
        [Required(ErrorMessage = "Debe escribir el nombre de la tecnología.")]
        [StringLength(300,ErrorMessage = "Máximo 300 caracteres.")]
        [Display(Name = "Nombre de la tecnología")]
        public string nombre { get; set; }
    
        public virtual ICollection<candidato> candidato { get; set; }
    }
}
